# git-check-mailmap
# Autogenerated from man page /run/current-system/sw/share/man/man1/git-check-mailmap.1.gz
complete -c git-check-mailmap -l stdin -d 'Read contacts, one per line, from the standard input after exhausting contact…'

