# git-update-server-info
# Autogenerated from man page /run/current-system/sw/share/man/man1/git-update-server-info.1.gz
complete -c git-update-server-info -s f -l force -d 'Update the info files from scratch'

