# git-merge-base
# Autogenerated from man page /run/current-system/sw/share/man/man1/git-merge-base.1.gz
complete -c git-merge-base -s a -l all -d 'Output all merge bases for the commits, instead of just one'
complete -c git-merge-base -l octopus -d 'Compute the best common ancestors of all supplied commits, in preparation for…'
complete -c git-merge-base -l independent -d 'Instead of printing merge bases, print a minimal subset of the supplied commi…'
complete -c git-merge-base -l is-ancestor -d 'Check if the first <commit> is an ancestor of the second <commit>, and exit w…'
complete -c git-merge-base -l fork-point -d 'Find the point at which a branch (or any history that leads to <commit>) fork…'
complete -c git-merge-base -l -o---1---o---o---o---A -d 'the merge base between A and B is 1'
complete -c git-merge-base -l -2---1---o---o---o---A -d 'the result of git merge-base A B C is 1'
complete -c git-merge-base -l -1---o---A -d '    \\ /      X     / \\'
complete -c git-merge-base -l -2---o---o---B -d 'both 1 and 2 are merge bases of A and B'
complete -c git-merge-base -l -o---o---B1--o---o---o---B -d '        \\          B0           \\            D0---D1---D (topic) where origin…'

