# git-version
# Autogenerated from man page /run/current-system/sw/share/man/man1/git-version.1.gz
complete -c git-version -l build-options -d 'Include additional information about how git was built for diagnostic purposes'

