# git-credential-store
# Autogenerated from man page /run/current-system/sw/share/man/man1/git-credential-store.1.gz
complete -c git-credential-store -l file -d 'Use <path> to lookup and store credentials'

