# scalar
# Autogenerated from man page /run/current-system/sw/share/man/man1/scalar.1.gz
complete -c scalar -s C -d 'Before running the subcommand, change the working directory'
complete -c scalar -s c -d 'For the duration of running the specified subcommand, configure this setting'
complete -c scalar -l full-clone -d 'git sparse-checkout set to expand the set of directories you want to see, or …'
complete -c scalar -s b -l branch -d 'Instead of checking out the branch pointed to by the cloned repository\'s HEAD…'
complete -c scalar -l single-branch -d 'Clone only the history leading to the tip of a single branch, either specifie…'
complete -c scalar -l src -d 'By default, scalar clone places the cloned repository within a <entlistment>/…'
complete -c scalar -l no-src -d 'to place the cloned repository directly in the <enlistment> directory'

